config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#home'
  get 'static_pages/home'
  get '/contact',   to: 'static_pages#contact'
  get '/about',     to: 'static_pages#about'
  get '/signup',    to: 'users#new'
  post '/signup',   to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end
  
  def about
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About Me") %>

<h1>About Me</h1>

<h1>Julie-Anne Glennon</h1>
<h2> student number: 2864184</h2>

<p>
    My name is Julie-Anne Glennon. I am a confident and mature student entering my fourth year of a BScH Computer Science Degree, 
excelling at all modules, gaining above 83% PPA each year. As demonstrated, through my work for the Make A Wish Foundation 
and my recent 9 month internship (taken as part on my degree) in the IT department of the Uniphar Group, 
I have excellent leadership, project management and communication skills, developing and maintaining strong relationships 
with both fundraisers and volunteers while working for the Make-A-Wish Foundation and regularly meeting and exceeding event targets.  
</p>
<p>
    I have been programming in java for the past number of years. I have also developed several websites for friends and family.
    In october last year I started teaching myself Ruby on Rails with the aid of Code School's Rails for Zombies series.
</p>
	
	
	
	<h3>Subjects I am Studing </h3>
	
	<ul>
	<li>WebFrameworks</li>
	<li>Cloud Services and Platforms</li>
	<li>Emerging Technology</li>
	<li>Distributed Systems</li>
	<li>Managing Big Data</li>
	<li>Concurrent Programming</li>
	<li>Advanced Network Theory</li>
	</ul>
	
	
	
    <h3>Interesting Facts:</h3>
	<ul>
	<li>I am studying a BSc in Computer Science at 38... and feeling .... OLD! </li>
	<li>I live in Killiney</li>
	<li>I have 6 dogs</li>
	<li>I have worked for the Make-A-Wish Foundation which was truely inspiring!</li>
	<li>I love my Mac!</li>
	</ul>
	
	<p><strong>My Favourite Films</strong></p>
	<ol start="5">
	<li>Finding Nemo</li>
	<li>Copycat</li>
	<li>Alien</li>
	<li>Aliens</li>
	<li>The Girl With The Dragon Tattoo</li>
	</ol>

	<h4>My most visited websites</h4>
	<ul>
	<li><a href="https://www.codeschool.com/?searchsegment=ppcbrand&aid=701j0000002BMf7AAG&promo=&oid=&utm_source=google&utm_medium=paidsearch&utm_campaign=CS_Brand-google&utm_content=&utm_term=&gclid=CK3l54qo4dICFeeV7QodG9MA_w">CodeSchool</a></li>
	<li><a href="http://moodle.gcd.ie/moodle/" title="Griffith College Moodle Page">Moodle</a></li>
	<li><a href="http://www.w3schools.com/html/html5_intro.asp" title="w3schools">HTML5</a></li>
	<li><a href="http://makeawish.ie/" title="Make-A-Wish">Make-A-Wish Foundation</a></li>
	<li><a href="https://www.google.ie/?gws_rd=cr&ei=cG9hUpOUF6y07Qa8xoDgCw" title="Google">Search Engine</a></li>
	</ul>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>

<h1>Contact Me</h1>
<p>Please contact me at <a href="https://www.linkedin.com/in/julie-anne-glennon-18783157">Linkedin</a>
or you can email me at : Julieanne2864184@gmail.com</p>

 

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to Assignment 2</h1>
<h2>This is the home page for my Resume</h2>

<%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>

 </div
 
 <%= link_to image_tag("rails.png", alt: "Rails logo"),
            'http://rubyonrails.org/' %>